import type { Metadata } from "next";
import { Roboto_Mono } from 'next/font/google'
import "./globals.css";
import Navbar from "./(components)/navbar/Navbar";
import myUser from "./actions/getUser";
import getBasketItem from "./actions/getBasketItem";

const inter = Roboto_Mono({
  variable: '--font-inter',
  weight: '600',
  subsets: ['cyrillic'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await myUser();
  const basketItems = await getBasketItem();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar 
        basketItem={basketItems}
        myUser={currentUser}
        />
        
        {children}
      </body>
    </html>
  );
}
